sudo: required

language: java

services:
  - docker

after_success:
  - docker login -e="jkriptos+docker@gmail.com" -u="jkriptos" -p="kakarotto"
  - docker build -t wu/async-api ./docker-build
  - docker images
  - docker push wu/async-api